/**
 ******************************************************************************
 * @file       uobj_$${NAME}.h
 * @author     王乐辉<wanglehui8357@163.com> Copyright (C) 2013.
 * @brief      declaration of the $${NAME} Export Data Type. This file has been
 *             automatically generated by the GearCoder.
 *             $(DESCRIPTION)
 * @note       This is an automatically generated file.
 *             !!!DO NOT modify manually!!!.
 ******************************************************************************
**/

#ifndef _UOBJ_$${NAMEUC}_H_
#define _UOBJ_$${NAMEUC}_H_

#include "datatype.h"
#include "statuscode.h"

#ifdef __cplusplus
extern "C"
{
#endif

// Export data type constants
#define UOBJ_$${NAMEUC}_ID           $$TYPEID
#define UOBJ_$${NAMEUC}_INSTCNT      $$INSTCNT
#define UOBJ_$${NAMEUC}_MEMBERCNT    $$MEMBERCNT
#define UOBJ_$${NAMEUC}_NAME         "$${NAME}"

// data type define
typedef struct {
$$MEMBERS_DEF
} UObj_$${NAME};

// Generic interface functions
extern void $${NAME}_Init(void);

// Utility for get or set member value
$${MEM_GETTER_DEC}
$${MEM_SETTER_DEC}

$${VALUE_GETTER_DEC}
$${VALUE_SETTER_DEC}

#ifdef __cplusplus
}
#endif

#endif // ~_UOBJ_$${NAMEUC}_H_
